### ISSUE TITLE
Getting stocktwits Stream

### ISSUE THREAD

**Issue by rashad101** [hamx0r/stocktwits#1]
If I want to get stock stream only and save it as *.json what should be the python code ?
Can you help me on that?

**Comment by hamx0r** [comment]
Sure!  For a single stock, you don't need to make a Watchlist - you can just use `api.get_stock_stream()`.  There are the `Requests` and `GAE` implementations to chose from.  I plan to eventually do away with the GAE variant.  

ie. `get_stock_stream('AAPL')`

Note that you'll need to call it periodically (ie in a loop or cron job) because it doesn't really stream anything - it just sends you the last 30 messages.  Each message has an `id`, so if you make your code remember the last message id, then you can use it in the `params` dict so that you only get new messages each time you call.  This sample will get messages every 10 secs, and only get the newest ones

```
msgs = get_stock_stream('AAPL')
while True:
    last_msg_id = msgs[-1]['id']
    params = {since_max: last_msg_id}
   time.sleep(10) 
    # Now when you call for more stock messages, you'll only get new ones
   get_stock_stream('AAPL', params)
```
